---
uid: frontend-modules:diagram:flowchart
title: "Flow Diagram"
type: diagram
diagram_type: flowchart
created: 2026-01-16
source: 02-modules/frontend/index.md
---

```mermaid
flowchart TD
    GET__api_users["GET /api/users"]

```
