---
uid: entities:diagram:erd
title: "Entity Relationship Diagram"
type: diagram
diagram_type: erd
created: 2026-01-17
source: 01-domain/entities.md
---

```mermaid
erDiagram
    {{name}} {

    }
```
