import * as fs from 'fs';
import * as path from 'path';

export class OutputWriterSkill {
    createStructure(baseDir: string, projectSlug: string): string {
        const specDir = path.join(baseDir, `${projectSlug}-spec`);

        // Create directories
        this.ensureDir(specDir);
        this.ensureDir(path.join(specDir, 'architecture'));
        this.ensureDir(path.join(specDir, 'analysis', 'core'));
        this.ensureDir(path.join(specDir, 'analysis', 'data'));
        this.ensureDir(path.join(specDir, 'analysis', 'integration'));
        this.ensureDir(path.join(specDir, 'analysis', 'security'));
        this.ensureDir(path.join(specDir, 'analysis', 'ops'));
        this.ensureDir(path.join(specDir, 'delta'));
        this.ensureDir(path.join(specDir, 'v1'));

        // Create README
        const readmeContent = `# ${projectSlug} Specification\n\nGenerated by RepoSpecZero.\n`;
        fs.writeFileSync(path.join(specDir, 'README.md'), readmeContent);

        return specDir;
    }

    writeAnalysisFile(specDir: string, category: string, filename: string, content: string) {
        const filePath = path.join(specDir, 'analysis', category, filename);
        fs.writeFileSync(filePath, content);
    }

    writeSpecZero(specDir: string, content: string) {
        fs.writeFileSync(path.join(specDir, 'spec_zero.md'), content);
    }

    private ensureDir(dir: string) {
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }
    }
}
